language: python
python:
- "3.6"
- "3.7"
- "3.8"
- "3.9"

before_install:
  - python --version
  - pip --version
  - pip install -U pip
  - pip install -U setuptools
  - pip install -U numpy

install:
  - pip install .
  - pip list

script:
  - pytest -Wignore
